[cloudflare.api]
base_url = "https://api.cloudflare.com/client/v4"
zone_id = "89560cdd783e35f7a9d718755ea9c656"
token = "9QjEiXC4B26tgshHZjuZ57kJcjaChSSsDfzUvfYQ"

[cloudflare.dns]
base = "n0des.xyz"
ttl = 300

[database]
url = "postgres://blockvisor:password@localhost:25432/blockvisor_db"
max_conns = 10
min_conns = 2
max_lifetime = "1d"
idle_timeout = "2m"

[email]
template_dir = "emails"
sendgrid_api_key = "123"
ui_base_url = "https://app.dev.blockvisor.com"

[grpc]
request_concurrency_limit = 128

[log]
environment = "dev"
filter = "info,grpc_tests=debug,tower_http=off"

[log.opentelemetry]
endpoint = "http://localhost:24317"
export_interval = "100ms"

[mqtt]
server_address = "127.0.0.1"
server_port = 21883
username = "blockvisor"
password = "password"

[server]
ip = "0.0.0.0"
port = 8080

[store]
prefix = "chains"
url = "https://r2.dev"
expiration = "1h"
aws_region = "eu-west-2"
aws_access_key_id = "<your value>"
aws_secret_access_key = "<your value>"

[store.bucket]
archive = "archive"
bundle = "bundle"

[stripe]
secret = "sk_test_51KfoP7B5ce1jJsfTHQ9i7ffUhQwUatBZ9djf4hKjqAXOB194aH5pHiJM1icpiGTdIqxeoRbhHSgwPPszyEkcXZKg00B9m2zhIn"
url = "https://api.stripe.com/v1"

[token.secret]
jwt = "1245456"
refresh = "987654321"
password_reset = "019243439"

[token.expire]
token = "10m"
refresh = "20h"
refresh_host = "30d"
refresh_user = "20h"
password_reset = "5m"
registration_confirmation = "30m"
invitation = "168m"
